[[entries]]

name = "doctype1"
identifier = "local0001"

[[doctype.markers]]

key = "key1"
is = "value1"

[[entries]]

name = "doctype2"
identifier = "local0002"

[[doctype.markers]]

key = "key2"
is = "value2"
